def load_model(model_name, snapshot):
  """
  Load the model from file. Includes pointers to the prototxt file, 
  caffemodel file name, and other settings - image mean, base_image_size, vocab 
  """

def output_words(detection_file, eval_file, functional_words, threshold_metric, output_metric):
  """
  Output the words as generated by the model.
  """

def test_model(imdb, model):
  """
  Tests model and stores detections on disk
  """

def benchmark(imdb, model):
  # Load images from imdb

  # Compute predictions using the model

  # Get ground truth

  # Benchmark the output, and return a result struct


def test_img(im, net, base_image_size, means):
  """
  Calls Caffe to get output for this image
  """
  # Resize image

  # Subtract mean

  # Permute Axis

  # Pass into Caffe

  # Get outputs and return them 
